### ISSUE TITLE
dependency could be much smaller

### ISSUE THREAD

**Issue by cmonacaps** [w8r/splay-tree#12]
In a production application I'm tasked with maintaining, the dependency picture is kind of bad already, and here's how the install looks:
```
npm i --dry-run splaytree
+ splaytree@3.0.1
added 74 packages, updated 1 package and audited 33184 packages in 11.104s
found 311 vulnerabilities (69 low, 13 moderate, 228 high, 1 critical)
```
Pretty surprised at "added 74 packages" for a basic algo, but I think the benchmark file increases it a lot.  Imo that should be factored into a separate package in order to provide the algo without overhead.

**Comment by w8r** [comment]
I checked it, and it's not what I am seeing: only 1 package is installed. In fact, `splaytree` has 0 dependencies, which is reflected in its `package.json`. 

I think, what is happening in your case is that you have some loose dependencies in your `package.json` and they were automatically satisfied by your call.

Feel free to re-open if you would be able to reproduce it in an empty project or after a clean `npm install`.
