### ISSUE TITLE
Remove method sometimes fails to remove the minimum node

### ISSUE THREAD

**Issue by BrandonQDixon** [w8r/splay-tree#42]
Sometimes, in the case where I attempt to retrieve and remove the minimum node from the tree, which I've just retrieved, the removal fails to take place.

Here is a minimal reproduction of my code:
```
const cellTree = new SplayTree<HexokuCellConstraint>(
    HexokuCellConstraintComparator.bind(HexokuCellConstraintComparator, visitor)
);
for (const cell of cells) {
    cellTree.insert(cell);
}

/** ... unrelated code omitted ... **/
const cell = cells.min()!;
const tmpOne = cells.size;
cells.remove(cell);
const tmpTwo = cells.size;

console.log(`${tmpOne} <> ${tmpTwo}`); // 7 <> 7 (indicating nothing happened)
```

**Comment by BrandonQDixon** [comment]
Please disregard, surprisingly, the comparator that I'm using is causing some kind of issue with how the tree internally structures itself. I became suspicious after seeing the same behavior in other libraries.

**Comment by w8r** [comment]
Cheers!
